### ISSUE TITLE
Consider using logging library instead of System.out

### ISSUE THREAD

**Issue by joemccall86** [Countly/countly-sdk-java#14]
We're running the Countly SDK in our back-end application and would like our logging to be centralized on our preferred logging library. That's currently impossible with logs printed to System.out. If you want to avoid a third-party dependency for logging, could you at least log using [java.util.logging](https://docs.oracle.com/javase/8/docs/api/java/util/logging/package-summary.html)?

**Comment by ArtursKadikis** [comment]
By default the SDK still logs to the console, but now there is also a log listener mechanism. More info here:
https://support.count.ly/hc/en-us/articles/360037813891-Java#log-listener

With this you can guide the generated logs to whatever service you may require.
