### ISSUE TITLE
Once stopped it cannot be started again

### ISSUE THREAD

**Issue by AshStefanOltmann** [Countly/countly-sdk-java#16]
In my app settings I want the user to have an switch where he can opt-in and opt-out to statistics at any time and this should have an immediate effect.

My `startStatisticLogging()` method looks like this:
```
            if (!Countly.isInitialized()) {

                val config: Config = Config(
                    STATISTICS_SERVER_URL,
                    STATISTICS_APP_KEY
                )
                    .enableFeatures(
                        Config.Feature.Events,
                        Config.Feature.Views,
                        Config.Feature.Sessions
                    )
                    .setCustomDeviceId(installId)
                    .setDeviceIdStrategy(Config.DeviceIdStrategy.UUID)

                val targetFolder = File(".")

                Countly.init(targetFolder, config)
            }
```

I stop the SDK using `Countly.stop(true)`. This works all fine.

But if I try to switch the statistics back on I get this:
```
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@41ecb4d2[Not completed, task = ly.count.sdk.internal.Tasks$2@22578833] rejected from java.util.concurrent.ThreadPoolExecutor@ec6175d[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 26]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2055)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1355)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
	at java.base/java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:719)
	at ly.count.sdk.internal.Tasks.run(Tasks.java:97)
	at ly.count.sdk.internal.Tasks.run(Tasks.java:68)
	at ly.count.sdk.internal.Storage.readAsync(Storage.java:225)
	at ly.count.sdk.internal.Storage.readAsync(Storage.java:212)
	at ly.count.sdk.internal.Storage.read(Storage.java:196)
	at ly.count.sdk.internal.SDKCore.prepareConfig(SDKCore.java:44)
	at ly.count.sdk.internal.SDKCore.init(SDKCore.java:60)
	at ly.count.sdk.java.CountlyLifecycle.init(CountlyLifecycle.java:47)
```

Is there a reliable way how I can turn sending off and on?

First I was thinking the `giveConsent()` and `removeConsent()` might be the answer to that, but in my tests this also did not have an immediate effect.

**Comment by ArtursKadikis** [comment]
Hello, "stop" is similar to "halt" in Android in the sense that it's a destructive "stop" button. Currently it is not designed for the SDK to be restarted afterwards, until the app is restarted.

Currently there is no mechanism in our SDK's to "stop" and "resume" SDK operations on demand.

Like mentioned in the Android SDK issue, the closest thing for that is handling of consent. Removing all consent should prevent tracking of additional information, though it would still try to send previosuly recorded data.

**Comment by AshStefanOltmann** [comment]
As said in the Android SDK issue removing and giving consent has no immediate effect.

So a "stop" and "resume" is currently unsupported and it looks not like you are going to support it in the future. Noted.

**Comment by ArtursKadikis** [comment]
We have some plans of a "pause/resume" functionality for the future, but that would use a different API.

On the note of "immediate effect". Additional data can not be recorded immedietelly, there is no lag in that.
If additional data is still being recorded then that is either a bug a an unexpeted issue with the implementation.
Could you please share the source code of the implementation that you are using? For both the Java app and Android app (in the other thread).
